version: '3.5'

networks:
  default:

services:
  kafka:
    depends_on:
    - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: wurstmeister/kafka
    networks:
      default:
    p


    orts:
      - "9092:9092"

  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      default:
    ports:
    - "2181:2181"
