version: '3.5'

networks:
  default:

services:
  messaging:
    depends_on:
    - config
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: config:2181
      KAFKA_CREATE_TOPICS: "Products:1:1,Status:1:1"
    image: wurstmeister/kafka
    networks:
      default:
    ports:
    - "9092:9092"

  config:
    image: wurstmeister/zookeeper
    networks:
      default:
    ports:
    - "2181:2181"
